### ISSUE TITLE
On Windows: db setup fails if C:\tmp\ does not exist already

### ISSUE THREAD

**Issue by torogi94** [labstructbioinf/localpdb#15]
Hi!  
When using localpdb on Windows machines, where `C:\tmp\` does typically not exist, the setup of the local image fails (as no log file can be created there). It works when the `tmp` folder is manually created, though.

**Comment by jludwiczak** [comment]
Hi @torogi94 and thanks for sharing your observation. I must admit that `localpdb` wasn't tested thoroughly on Windows systems. We had an undocumented option to set the custom temporary file location, which now I made more visible both in the code and in the documentation. For now I'll close the ticket, feel free to open a new one in case you'll have further problems.
