### ISSUE TITLE
not able to setup plugins

### ISSUE THREAD

**Issue by FlorianWieser1** [labstructbioinf/localpdb#17]
Awesome project! This would save me a lot of time :)
However I struggle to download/install the plugins DSSP, Socket and PDBClustering. Are these still maintained? 

I don't think I'm doing something crazy wrong, I downloaded both, the .pdbs and the .mmCIFs and then tried to install the plugins with:
`localpdb_setup -db_path . -plugins DSSP PDBClustering Socket >> localpdb.log`

and got:

localpdb is up to date and set up in the directory '/home/florian_wieser/databases/PDB'.

Plugin(s): PDBClustering were already installed, use the '--update' option to sync them.

Setting up plugin: 'Socket'...
Attempting to install plugin 'Socket' for localpdb version(s): 20220603
Could not set up plugin 'Socket' for the localpdb version '20220603'

Setting up plugin: 'DSSP'...
Attempting to install plugin 'DSSP' for localpdb version(s): 20220603
Could not set up plugin 'DSSP' for the localpdb version '20220603'

Thank you in advance!
Florian

**Comment by jludwiczak** [comment]
Hi @FlorianWieser1 and thanks for interest in our project!

Indeed the plugins are a bit messy and errors are not fully understandable now. I plan to polish this feature soon and improve the documentation. 

Nevertheless, I think these steps should be helpful to make the plugins run for now:

- The plugin PDBClustering seems to be installed fine according to the logs.
- For plugin DSSP you may have to edit the DSSP binary location specified in the yml config - https://github.com/labstructbioinf/localpdb/blob/master/localpdb/plugins/config/DSSP.yml . To do so you'd have to either edit locally installed file (in your ~/.local/lib/pythonX.Y/site-packages/localpdb or similar location if you use virtualenv or conda) or fork the repo, edit there and install the package from your fork). After this it should work :) (keep in mind that mmCIF mirror sync is required for this plugin).
- For socket plugin the same trick should work (file: https://github.com/labstructbioinf/localpdb/blob/master/localpdb/plugins/config/Socket.yml ). It's important to have DSSP 2.3.0 installed beside the newest one for this plugin (Socket silently fails to work with new DSSP output format ). Also, before setting up the Socket you need to have the Biounit plugin installed.

Hope this'll help, let me know if you'll need additional assitance!
